apiVersion: v1
kind: Pod
metadata:
  name: pd
  labels:
    env: prod
spec:
  containers:
    - name: cnt
      image: avbk/myrepo_bk:socialmedia_app
      ports:
        - containerPort: 8501
  affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: env
                operator: In
                values:
                - prod
            topologyKey: "kubernetes.io/hostname"
    
